language: node_js
node_js:
  - 12
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/taxi_trips

before_script:
  - psql -c 'create database  taxi_trips;' -U postgres
  - psql -U postgres -d taxi_trips -a -f sql/tables.sql
  - psql -U postgres -d taxi_trips -a -f sql/data.sql

services:
  - postgresql